apiVersion: apps/v1
kind: Deployment
metadata:
  name: belajar-nodejs-dasar
  namespace: belajar-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belajar-nodejs-dasar
  template:
    metadata:
      labels:
        app: belajar-nodejs-dasar
    spec:
      containers:
      - name: app
        image: $DOCKERHUB_USERNAME/belajar-nodejs-dasar:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /  # Update this to your health check endpoint
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /  # Update this to your health check endpoint
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5