apiVersion: v1
kind: Service
metadata:
  name: belajar-nodejs-dasar
  namespace: belajar-nodejs
spec:
  selector:
    app: belajar-nodejs-dasar
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
  type: NodePort